version: 2
jobs:
  build:
    working_directory: ~/aerogear
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache:
          key: dependency-cache-{{ checksum "client/package.json" }}
      - run:
          name: install-dependencies
          command: "cd client && npm install"
      - save_cache:
          key: dependency-cache-{{ checksum "client/package.json" }}
          paths:
            - ./client/node_modules
      - run:
          name: run build
          command: "cd client && npm run build"

  publish_showcase_container:
    docker:
      # image for building docker containers
      - image: circleci/node:lts
    steps:
      - checkout
      # special workaround to allow running docker in docker https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker:
          version: 17.05.0-ce
      - run: | 
          npm i
          npm run build:prod
      - run: |
          cd server          
          TAG=$CIRCLE_TAG ../scripts/publish_showcase_container.sh
workflows:
  version: 2
  build_and_release:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish_showcase_container:
          filters:
            tags:
              only: /.*/
            branches:
              only: master
